### ISSUE TITLE
Wrong result with u8

### ISSUE THREAD

**Issue by i64** [kaitai-io/kaitai_struct_javascript_runtime#19]
The last byte of u8 is missing.

Example struct:
```yaml
meta:
  id: test
  endian: le

seq:
  - id: uu64
    type: u8
```

example data:
```python
"\xf7\x30\x8a\x1e\xce\xf2\xde\xe9\x12\x5f"
```

result:
- `0xE9DEF2CE1E8A3000`

expected result:
- `0xE9DEF2CE1E8A30F7`
